### ISSUE TITLE
Choice of Microcontrollers

### ISSUE THREAD

**Issue by nepython** [BitsRobocon/AutonomousDrone#7]
# Micro-controllers currently compiled: 
### This will give a brief review:
Controllers    | RAM | Current | Voltage | Base Price |  
---------------|-------|----------|---------|-----------|
 [JETSON TX2](https://www.nvidia.com/en-in/autonomous-machines/jetson-store/)|  8gb   |   0.81-2.5A      |  5.5-19.6V           |     $549           |
 [UDOO X86](https://www.fabtolab.com/udoo-x86-board) |8gb|1-3A|3.3.V|    $174            |
 [ODROID H2](https://www.fabtolab.com/boards/Odroid-Boards/odroid-H2-intel-quad-core-processor-2.5Ghz-4MiB-cache)| upto 32 gb|  0.286-1.572         |    14-20V     |      $110          |
 [ODROID N2](https://www.fabtolab.com/boards/Odroid-Boards/odroid-n2-boards-accessories/odroid-n2)| 4gb|    2A       |8-18V|       $79         |

#### My Personal Recommendation is : UDOO X86 II with a graphics card such as GTX 1060/ RX 570 (approx. cost 30K)

**PS**: We went ahead with Jetson Xavier NX after a [detailed comparision](https://docs.google.com/document/d/1VlRzQoiDqBNOb9F17Jquv_BLlc273zME1Ix-lSBXs04/edit?usp=sharing).

**Comment by nepython** [comment]
## [UDOO bolt V8/V3](https://www.fabtolab.com/udoo-bolt)
##### This is also a very good option with powerful GPU and ram options upto 32 GB.
### Price = [V8(30k)/V3(24k)](https://www.mouser.in/Search/Refine?Ntk=P_MarCom&Ntt=135138089)
But it has been launched quite recently and thus doesn't have any discussion forums, incase any problems emerge later on.

**Comment by NidheeshJain** [comment]
Owing to **extremely good documentation, active online community and undoubtedly one of the best computation power**, I think we should go for **Jetson TX2**, because while working with other boards we might face issues like optimizing CPU, GPU usage etc. Such issues will require a good amount of depth and as of now, I don't think we have the required skill-set to delve into it.
Recommendation from one of BITS Robocon alumni - Arjun, who is working on UAVs extensively, plays a factor in this decision.

**Comment by Div12345** [comment]
Carrier for Jetson module rather than using the development kit directly - 
Reason for using a carrier - https://www.electronicdesign.com/technologies/test-measurement/article/21802864/carrying-a-jetson-tx1

**Comment by hardesh** [comment]
Hello, I'm Harshal from ERC BITS Goa. I came across your project when one of our members put the link on the group. 

As for the main on-board computer, I think you guys should take a look at the new *Jetson Xavier NX*. Its small form factor will let you mount it on the frame.

**Comment by nepython** [comment]
@hardesh, I too suggested the same, sometime back in the team channel and we had discussed that **Jetson Xavier-nx** is a better option.
* It outperformed **TX2** by almost 10 times in many benchmark tests ([source](https://devblogs.nvidia.com/jetson-xavier-nx-the-worlds-smallest-ai-supercomputer/)).
* It is really small (as small as **Jetson Nano**)
* It also had an edge when it comes to the price ( ~ ₹41.7k)

Thanks, for taking out time to suggest us :smile: 

There are slight reservations though, the board has been launched very recently and thus
* doesn't has that big a community (which might result in more efforts on our side) and reviewers to do an independent assessment.

**Comment by hardesh** [comment]
I think you won't face a lot if issues even if you buy the Xavier NX. Last year, we bought the AGX Xavier and the only issue that we faced was regarding the fan on/off. These things are built pretty well and their forums have a lot of resources.

**Comment by NeelakshSingh** [comment]
Re-posting the link to the [detailed comparison](https://docs.google.com/document/d/1VlRzQoiDqBNOb9F17Jquv_BLlc273zME1Ix-lSBXs04/edit) here so that it is distinctly visible.

**Comment by nepython** [comment]
Final decision: Nvidia Jetson Xavier NX
